version: '3'

services:
  airflow:
    image: maybe   
    command: standalone
    ports:
      - "8080:8080"
    depends_on:
      - POSTGRES_AIRFLOW_DB
      - POSTGRES_CRICBUZZ_DB
      - chrome
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@POSTGRES_AIRFLOW_DB/airflow
      - AIRFLOW_CONN_HADOOP_CONNECTION=webhdfs://namenode:9870
      - AIRFLOW_CONN_CRICBUZZ_DB=postgresql://rajabala:rajabala@POSTGRES_CRICBUZZ_DB/Crickbuzz
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow
      - AIRFLOW_DB_MIGRATE='true'
      - AIRFLOW_WWW_USER_CREATE='true'
      - AIRFLOW_WWW_USER_USERNAME= airflow
      - AIRFLOW_WWW_USER_PASSWORD= airflow

    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    

  POSTGRES_AIRFLOW_DB:
    image: postgres:13
    ports:
      - "5432:5432"
    
    environment:
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
  POSTGRES_CRICBUZZ_DB:
    image: postgres:13
    ports:
      - "5433:5432"
    
    environment:
      - POSTGRES_DB=Crickbuzz
      - POSTGRES_USER=rajabala
      - POSTGRES_PASSWORD=rajabala

  
  
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:




